lukechampine/us

README.md
Actual go imports reference `lukechampine.com/us/`, not `github.com/lukechampine/us/`. Thus, to build the project out of the box with the `make` command you need to use the files installed from `go get lukechampine.com/us/...`, not `go get github.com/lukechampine/us/...`.
=> Update install documentation to reflect actual go imports

cmd/user/main.go, renter/contracts.go, renter/convert.go
Resolves #3.
The only departure from the proposal is that `user` isn't great about guiding you towards the `convert` command. The problem is that there are lots of places where `user` loads contracts, and I don't want to add code in every place that catches the specific version error and prints a nice message. So instead you'll get a generic error (`incompatible version (v1): convert to v2`) and hopefully infer that `user convert` is a valid command.
=> Add the host's public key to the contract header

go.mod, merkle/merkle.go, merkle/merkle_test.go, merkle/proof.go, renter/proto/session.go, renterhost/session.go, renterhost/session_test.go
Partially implements #29. See that issue for benchmarks.
=> Stream Merkle root computation when downloading

renter/proto/session.go, renter/renterutil/hostset.go, renterhost/session.go
Previously, we continued to use a `Session` even if an earlier RPC had returned an error. This meant that we were attempting to talk to a host that had closed its end of the connection, which caused confusing `broken pipe` errors.
The session code will now set a flag and close the connection when an I/O or authentication error occurs. The `HostSet` type will check this flag and automatically reconnect if necessary. I tested this by injecting random faults into `ghost` (timing out early 1/10th of the time), and all of the renterutil tests still passed, indicating that the code is now robust to transient errors.
Note that the errors are not suppressed; if a `Read` fails because too many hosts timed out, you'll still see the error. The difference is that now, if only one host failed due to a …
=> Reconnect Sessions if they close prematurely

renter/proto/renew.go, renterhost/encoding.go, renterhost/session.go
The `RenewAndClear` RPC is much the same as a standard `Renew`, except that it simultaneously "clears" the old contract. This causes renewals to behave less surprisingly: after a contract has been renewed, the old contract is no longer usable. Importantly, this allows the host to throw away the old contract instead of retaining it and submitting a storage proof.
=> Add support for RPCRenewAndClear

go.mod, go.sum
This fixes runtime panics in Go 1.14 caused by improper use of `unsafe.Pointer`.
=> mod: Update to bbolt@v1.3.4

go.mod, go.sum, renterhost/session.go, renterhost/session_test.go
With this commit and #46, MR https://gitlab.com/NebulousLabs/Sia/-/merge_requests/4348,
we can compare a host error with pre-defined errors for example
```go
errors.Is(err, host.ErrBadFileSize)
```
This code would work even if the error is wrapped by `erros.Wrap` or other 3rd party error libraries
such as go-multierror.
=> RPCError implements Is function

renter/renterutil/filesystem.go
=> renterutil: Handle errors in filepath.Walk

renter/renterutil/fileops.go
=> renterutil: Clamp maxWriteSize to 0

renter/proto/formcontract.go, wallet/builder.go, wallet/builder_test.go
This should reduce the likelihood of contract transactions being rejected by the tpool.
I also added a helper function for splitting large inputs into smaller ones. Doing this regularly should ensure that you always have non-limbo outputs available for forming contracts.
=> Prefer non-limbo outputs in contract transactions

renter/proto/renew.go, renter/proto/session.go
This fix will prevent the panic, but `siad` hosts will likely still reject the RPC with an error until the [upstream fix](https://gitlab.com/NebulousLabs/Sia/-/merge_requests/4630) is merged.
=> Fix underflow and add collateral leeway

renter/proto/renew.go, renter/proto/session.go, renter/proto/session_test.go, renter/renterutil/hostset.go
=> Allow custom timeouts in RPCLock

renter/proto/formcontract.go, renter/proto/renew.go, renter/proto/session_test.go
See #96.
Also removes support for non-clearing renewals. According to SiaStats, 90%+ of hosts now support `RenewAndClear`, so I think this is acceptable.
=> Add leeway to contract price

renter/proto/formcontract.go, renter/proto/renew.go
This reverts commit 0cdccdfff026ade293667f683d39d27d29d95d00. Adding this leeway resulted in contract transactions whose inputs did not equal their outputs.
=> Revert "proto: Add 5% leeway to contract price"

go.mod, go.sum, renter/proto/session_test.go, renterhost/session_test.go, wallet/dbstore.go, wallet/wallet.go
The `encoding` package has been moved out of `gitlab.com/NebulousLabs/Sia`. This means that if you use the current version of `Sia` in your `go.mod` file, and you also import `us`, you get errors because `us` expects to find `encoding` in `Sia`. This commit switches to the separate `encoding` module, which (I believe) prevents this breakage.
=> all: Use separate encoding package

merkle/merkle_test.go, merkle/proof.go
This bug caused the renter to erroneously report certain sector proofs (from the `SectorRoots` RPC) as invalid. The fix is kinda ugly, but I figured it was more important to get this merged right away.
=> merkle: Fix tail hash bug in (Build|Verify)SectorRangeProof

internal/ghost/host.go, internal/ghost/session.go, renter/renterutil/migrate_test.go
See https://github.com/lukechampine/us/issues/106#issuecomment-707398157
=> ghost: Fix Session race conditions

go.mod, go.sum, renterhost/mux/encryption.go, renterhost/mux/frame.go, renterhost/mux/mux.go, renterhost/mux/mux_test.go
This is an implementation of the https://gitlab.com/NebulousLabs/SiaMux multiplexer. It does not handle port mapping, logging, or bandwidth limiting -- just the network protocol. This is the protocol used for RHP3, so we need it in order for the renter to call RHP3 methods.
=> mux: Add renterhost/mux package

renterhost/mux/frame.go, renterhost/mux/mux.go, renterhost/mux/mux_test.go
Exported errors, more documentation, and better Write performance with 1000s of streams.
Current benchmarks:
```
BenchmarkConn               15664 ns/op         915.08 MB/s            0 B/op          0 allocs/op
BenchmarkRHP2               21776 ns/op         658.24 MB/s        14482 B/op          4 allocs/op
BenchmarkMux/1              16842 ns/op         851.08 MB/s            0 B/op          0 allocs/op
BenchmarkMux/2              37007 ns/op         774.67 MB/s            0 B/op          0 allocs/op
BenchmarkMux/10            177423 ns/op         807.90 MB/s            7 B/op          0 allocs/op
BenchmarkMux/100          1760469 ns/op         814.21 MB/s          221 B/op          0 allocs/op
BenchmarkMux/500          9458982 ns/op         757.69 MB/s         2814 B/op         22 …
```
=> Various mux improvements

host/chain.go, host/contracts.go, host/host.go, host/session.go, host/session_test.go, host/wallet.go, renter/proto/formcontract.go, renter/proto/proto.go, renter/proto/renew.go, renter/proto/session_test.go, renter/renterutil/client.go, renter/renterutil/filesystem_test.go, wallet/seedwallet.go
This prevents races between multiple consumers of `proto.Wallet`/`host.Wallet` that are constructing transactions. Previously, the following situation could arise:
- Goroutine A calls `FundTransaction`, which returns a transaction spending input X
- Goroutine B calls `FundTransaction`, which returns a transaction spending inputs X Y Z
- Goroutine A broadcasts its transaction successfully
- Goroutine B broadcasts its transaction, but the transaction is rejected because it double-spends X
In `muse` I worked around this by guarding calls to `FormContract`/`RenewContract` with a lock, but this had the unfortunate side effect of serializing all contract formation/renewal.
The new API requires consumers to explicitly discard inputs when they are finished with them. Consequently, …
=> wallet: Add input discarding

ed25519hash/batch.go, ed25519hash/batch_test.go, go.mod, go.sum
This isn't directly useful for anything in `us` (yet), but in theory it could be used in `Sia/types` to validate transactions a bit faster. More likely, we'll just switch to using `ed25519consensus` in a subsequent hardfork.
=> ed25519hash: Add batch verification

renter/renterutil/kv.go
Currently, PseudoKV always uses ParallelBlobUploader and ParallelBlobDownloader, but I think it's better to use SerialBlobUploader and SerialBlobDownloader if P = 1.
=> Use SerialBlobUploader and SerialBlobDownloader if P = 1

renter/renterutil/strategies.go
This PR fixes the issue https://github.com/lukechampine/us/issues/106#issuecomment-817186073.
=> Context based cancellation of acquiring a session

renter/renterutil/strategies.go
That error means the sector is already removed, and we can ignore it. 
Callers of `ParallelSectorDeleter.DeleteSectors` are also able to ignore the error. However, it's not easy to ignore a certain error from `HostErrorSet`. I thus think it's better `ParallelSectorDeleter.DeleteSectors` ignores it.
=> DeleteSectors ignores "could not find the desired sector"

renter/renterutil/strategies.go
Some functions didn't use `acquireCtx`. This PR fixes this problem.
=> Always use acquireCtx

renter/renterutil/fileops.go, renter/renterutil/hostset.go, renter/renterutil/kv.go, renter/renterutil/strategies.go
Since we need to know which error is returned, this PR exports those errors.
=> Export private errors in renterutil package

renter/proto/formcontract.go, renter/proto/renew.go
When using the `SiadClient` the renter signatures were not being sent to the host causing the host to throw `invalid signature`. 
https://github.com/lukechampine/us/blob/36e1081712379a6af2b3f49ca4aadfb1b1786625/renter/renterutil/client.go#L162
=> fix invalid signature when using SiadClient

go.mod
This is necessary because the version containing the retraction must be the highest (as determined by `@latest`)
=> mod: Retract v1.13.1 as well
