cmd/user/contracts.go
renter/contracts.go
renter/proto/downloader.go
renter/proto/formcontract.go
renter/proto/negotiate.go
renter/proto/proto.go
renter/proto/renew.go
renter/proto/uploader.go

Resolves #7.
The only departure from the proposal is that the `proto.ContractKey` interface also requires a `PublicKey` method, since we send the renter's public key to the host.

Refactor secret key management in proto

---

renter/proto/session.go

I keep getting burned by too-short deadlines. Hopefully the new defaults are so extreme that they only ever need to be shortened, not lengthened.

proto: Increase Session deadlines

---

merkle/blake2b/gen.go

Hopefully this is useful to other people writing code with `avo`!

blake2b: Document asm generation more thoroughly

---

internal/ghost/host.go
internal/ghost/session.go
renter/proto/session.go
renter/proto/session_test.go

Also catch finalized contracts in `RPCLock`.

Add RenewAndClear test

---

internal/reedsolomon/matrix.go
internal/reedsolomon/matrix_test.go
internal/reedsolomon/reedsolomon.go
internal/reedsolomon/reedsolomon_test.go

I swear, this is the last one.

reedsolomon: Remove more code, cleanup comments

---

renter/renterutil/fileops.go
renter/renterutil/filesystem.go
renter/renterutil/filesystem_test.go

Fix panic caused by misaligned writes

---

renter/proto/proto.go
renter/proto/session.go
renter/proto/session_test.go
renter/renterutil/hostset.go

This allows clients to collect statistics about the performance of individual hosts. Some guidance is provided re: using these stats to measure bandwidth, to which I will add another warning: performance measurements will be affected by how many hosts you are communicating with in parallel, so be sure to compare the `Timestamp` and `Elapsed` fields of each `RPCStats` to determine when a set of RPCs overlapped. Still, even without that adjustment, these stats should give a reasonable indication of which hosts are high-quality and which are not.

proto: Add RPCStats and RPCStatsRecorder

---

renter/proto/renew.go

proto: Prevent underflow in Renew

---

renter/proto/session.go

proto: Expose ErrInsufficientFunds

---

renter/proto/session.go
renter/renterutil/filesystem.go

For very large contracts (>2 TB of data), the size of all of the sector roots exceeds the host's default maximum per-RPC download size. This PR limits the number of roots requested by any single `SectorRoots` RPC, such that we never download more than 4 MiB at a time.

"Paginate" SectorRoots requests

---

renter/proto/session.go

Previously the `maxLen` was fixed at 4096, which severely limited the number of roots that could be requested.

proto: Use dynamic maxLen for SectorRoots RPC

---

renter/proto/session.go

Fixes https://github.com/lukechampine/us/issues/80

proto: Ensure RenterFunds >= 5*BaseRPCPrice

---

wallet/builder.go
wallet/builder_test.go

While implementing the `walrus-cli` output splitting command, I realized this is a much better API.

wallet: Overhaul DistributeFunds

---

renter/proto/formcontract.go
renter/proto/session.go

proto: Make ErrInsufficientFunds more generic

---

renter/proto/proto.go
renter/proto/proto_test.go
renter/proto/session.go

proto: Add NewUnlockedSessionFromConn

---

go.mod
go.sum
renter/proto/formcontract.go

proto: Avoid funding with outputs spent in Limbo

---

wallet/wallet.go

This should allow for more accurate accounting; namely, for any transaction, you can compute the effect on the wallet's balance.

wallet: Add input values to Transaction

---

renter/proto/renew.go
renter/renterutil/client.go

Fix Renew cost calculation

---

renter/proto/renew.go

This is a bit surprising. We definitely don't want contracts to be an unrenewable state, so we should either update the host to be more permissive in its renewal checks (if possible) or have the host's `SetSettings` method reject settings that would lead to this situation.

proto: Check for unsatisfiable host settings

---

go.mod
go.sum
merkle/merkle_test.go
renter/meta.go
renter/meta_test.go
renterhost/session.go
renterhost/session_test.go
wallet/bip39_test.go
wallet/seed.go
wallet/seedwallet_test.go
wallet/wallet_test.go

all: Use new frand helpers

---

renter/renterutil/metadb.go

Initialize meta field in EphemeralMetaDB

---

renter/renterutil/hostset.go

Previously, if a session was created but the `Lock` RPC failed, the session would be closed, but non-nil. Later, if `reconnect` was called again, `reconnect` would return the closed session immediately if less than 2 minutes had elapsed. The caller would then get mysterious errors when trying to call an RPC on the (closed) session.
This commit should fix the problem by requiring non-nil sessions to also be non-closed in `reconnect`.

renterutil: Make HostSet reconnection more robust

---

renter/proto/formcontract.go
renter/proto/renew.go

#130 introduced a bug; this fixes it

proto: Remove TransactionSignature before sending contract

---

wallet/builder.go

Fixes https://github.com/lukechampine/walrus-cli/issues/16

wallet: Fix DistributeFunds fee calculation

---

renter/renterutil/hostset.go

This removes the need for separate `SetRPCStatsRecorder`, `SetReadDeadline`, etc. methods. It's more powerful anyway, since you can branch on the session's `ID` or `HostKey`. For example:
```go
hs.OnConnect(func(s *proto.Session) {
s.SetRPCStatsRecorder(stats)
if s.HostKey() == someSlowHost {
s.SetReadDeadline(foo)
}
})
```

renterutil: Add onConnect callback for HostSet

---

go.mod
go.sum
renterhost/session.go

Fixes https://github.com/lukechampine/us/issues/139

Update for Go 1.15

---

wallet/seedwallet.go

wallet: Mark funding outputs as used

---

renterhost/session.go

In `RPCRead`, the host needs to continuously attempt to Read from the renter while it simultaneously Writes responses to it. This causes a data race on the `err` and `closed` fields of `Session`. Fixed by adding a mutex that guards these fields.
Fixes #154

renterhost: Prevent data race during overlapping read/write

---

renter/renterutil/hostset.go

This PR fixes https://github.com/lukechampine/us/issues/166.

HostSet.Close releases locks

---

go.mod

At long last, this mistake can be corrected.

mod: Retract v1.13.0
